[package]
name = "fluent_native"
version = "0.2.0"
authors = []
edition = "2018"

[lib]
name = "fluent_native"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
rustler = "0.21.0"
lazy_static = "1.0"
fluent = "0.10.2"
unic-langid = "0.8.0"